services:
  - type: web
    name: crack-detection
    runtime: python
    pythonVersion: 3.12.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false